In [1]:
import torch 

In [7]:
x = torch.empty(3,1)
x

tensor([[2.3022e-26],
        [4.5908e-41],
        [2.3577e-26]])

In [6]:
y = torch.rand(2,2)
y

tensor([[0.6999, 0.8341],
        [0.2353, 0.1806]])

In [11]:
x = torch.ones(2,2,dtype= torch.int32)
print(x.size())
x

torch.Size([2, 2])


tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [15]:
x = torch.tensor([1,2,4.6])#list
print(x.size())
x

torch.Size([3])


tensor([1.0000, 2.0000, 4.6000])

In [18]:
x= torch.rand(3,3)
y= torch.rand(3,3)
z= x + y
# z = torch.sub(x,y)
# z = torch.mul(x,y)

z = torch.add(x,y)
# y = add_(x)  # inplace
# y = mul_(x)  # inplace

z

tensor([[1.0306, 1.4993, 0.0719],
        [1.7124, 0.6576, 0.3303],
        [1.1313, 0.6423, 0.9898]])

# Slacing

In [21]:
x = torch.rand(5,3)
print(x)
print(x[:,0])  # column 0 
print(x[-1])  # last row 
print(x[1,1].item()) # will gives actual value 

tensor([[0.7112, 0.0823, 0.7723],
        [0.9151, 0.6163, 0.7417],
        [0.4597, 0.1815, 0.6916],
        [0.9269, 0.1911, 0.5953],
        [0.1792, 0.9985, 0.0832]])
tensor([0.7112, 0.9151, 0.4597, 0.9269, 0.1792])
tensor([0.1792, 0.9985, 0.0832])
0.6163166761398315


In [25]:
x = torch.rand(4,4)
# y = x.view(16)
y = x.view(-1,8)
y

tensor([[0.5833, 0.4328, 0.6505, 0.9374, 0.6222, 0.7998, 0.4658, 0.1408],
        [0.5971, 0.9233, 0.0679, 0.4484, 0.0486, 0.6778, 0.6369, 0.2935]])

In [34]:
# from tensor to numpy array 
import numpy as np
a= torch.ones(5)
print(type(a),a)
b = a.numpy()
print(type(b),b)
print(a.add_(1))
# print(b.add_(1)) #numpy.ndarray' object has no attribute 'add_'

<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])


In [37]:
# from array to tensor
a= np.ones(5)
print(type(a),a)
b = torch.from_numpy(a)
b

<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [41]:
if torch.cuda.is_available():
    # use gpu
    device = torch.device("cuda")
    x = torch.ones(5,device= device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu") # we move to cpu because numpy dont deal with gpu
print(x)
print(y)

tensor([[0.5833, 0.4328, 0.6505, 0.9374],
        [0.6222, 0.7998, 0.4658, 0.1408],
        [0.5971, 0.9233, 0.0679, 0.4484],
        [0.0486, 0.6778, 0.6369, 0.2935]])
tensor([[0.5833, 0.4328, 0.6505, 0.9374, 0.6222, 0.7998, 0.4658, 0.1408],
        [0.5971, 0.9233, 0.0679, 0.4484, 0.0486, 0.6778, 0.6369, 0.2935]])


In [42]:
#tell pytorch we need this tensor to calculate the graident later 
# for optimazation we need gradent
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)